-----
# ** 데이터 처리: 넘파이**

-----


# 1. 배열  
배열(array)이란 숫자를 일정하게 나열한 자료 구조
 

## 1.1 파이썬 배열의 특징
    리스트로 관리한다.
  * 따라서 배열의 크기를 자유롭게 늘리고 줄일 수 있다. 
  * 따라서 각 원소의 크기 또한 고정되어 있지 않다.
  * 그래서 **동적 배열**(dynamic array)라고 부른다. 
* 내부적으로는 전통적 의미의 배열로 처리한다.
  * 따라서 배열 요소에 인덱스(index)가 부여된다.
  * 따라서 각종 배열 메서드를 사용할 수 있다. 
* 어쨌든 **파이썬 배열 = 파이썬 리스트**라고 보면 된다.

## 1.2 파이썬 배열 다루기
파이썬에서 배열을 다룬다는 것은 곧 파이썬 리스트를 다룬다는 말입니다. 따라서 리스트를 가지고 할 수 있는 일을 그대로 하면 됩니다. 

In [ ]:
# 1차원 배열 선언(리스트 선언)과 할당
일차원_배열 = [1, 2, 3, 4, 5]  # 우변에서 배열을 선언, =로 할당 연산.
print(일차원_배열)

[1, 2, 3, 4, 5]


In [ ]:
# 2차원 배열 선언과 할당
이차원_배열 = [[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
print(이차원_배열)

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]


In [ ]:
# 3차원 배열 선언과 할당
삼차원_배열 = [[[ 1,  2,  3,  4,  5], [ 6,  7,  8,  9, 10]],  
               [['가', '나', '다', '라', '마'], ['바', '사', '아', '자', '차']]]
print(삼차원_배열)

[[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], [['가', '나', '다', '라', '마'], ['바', '사', '아', '자', '차']]]


# 2. 넘파이의 기본
앞에서 보았듯이 파이썬에서는 배열(array)이라는 데이터 형식을 지원하지 않으므로 리스트(list)를 사용해 전통적인 의미의 배열을 사용

<U> 리스트는 포인터 기반 리스트 그래프 구조로 형성되어 컴퓨터 메모리 상에서 흩어져 있게 되지만, 넘파이 배열은 C 언어와 마찬가지로 컴퓨터 메모리의 연접 공간에 배열을 넣고 관리하기 때문에, 파이썬 리스트보다 처리 속도 면에서 비교할 수 없을 정도로 빠르다.</U>

<U>리스트를 만들 때 각 성분의 데이터 형식이 달라도 되지만, 넘파이 배열에서는 각 성분의 데이터 형식이 같아야한다.</U>

## 2.1 넘파이 패키지 불러오기

In [ ]:
# 패지키만 불러오기 
import numpy

In [ ]:
# 넘파이 패키지를 불러와서 별명을 짓기
import numpy as np  # np는 관례적으로 지어 부르는, 넘파이의 별칭이다.

## 2.2 넘파이 배열 형성


### 2.2.1 넘파이 배열 형성

In [ ]:
# (1) 넘파이 배열을 만들려면 먼저 리스트 형식으로 배열을 구성해 준다. 
리스트형_배열 = [1, 2, 3, 4, 5]  # 우변은 배열 정의 부분, =은 할당 연산.
print(리스트형_배열)

[1, 2, 3, 4, 5]


In [ ]:
# (2) 그러고 나서 리스트 형식 배열을 넘파이 배열로 캐스팅한다. 
넘파이형_배열 = np.array(리스트형_배열)
print(넘파이형_배열)

[1 2 3 4 5]


### 2.2.2 넘파이 배열의 데이터 형식
넘파이 배열의 데이터 형식은 ndarray입니다. 이는 n차원 배열(n-dimensional array)이라는 뜻을 지닌 이름입니다.

In [ ]:
# [보충] 넘파이형 배열의 데이터 형식(data type, 자료형) 알아보기
type(넘파이형_배열)

numpy.ndarray

### 2.2.3 리스트 값을 넣어 배열 형성하기

In [ ]:
# 1차원 리스트 값을 바로 넣어 넘파이 형식 배열 형성하기
넘파이형_1차원_배열 = np.array([1, 2, 3, 4, 5])
print(넘파이형_1차원_배열)

[1 2 3 4 5]


In [ ]:
# 2차원 리스트 값을 넣어 넘파이 형식으로 된 2차원 배열을 형성하기
넘파이형_2차원_배열 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(넘파이형_2차원_배열)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [ ]:
# 3차원 리스트 값을 넣어 넘파이 형식으로 된 3차원 배열을 형성하기
넘파이형_3차원_배열 = np.array([[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], [[1.0, 2.0, 3.0, 4.0, 5.0], [6.0, 7.0, 8.0, 9.0, 10.0]]])
print(넘파이형_3차원_배열)  # 각 수치가 모두 부동소수점 형식으로 통일되었다는 점에 주목하자.

[[[ 1.  2.  3.  4.  5.]
  [ 6.  7.  8.  9. 10.]]

 [[ 1.  2.  3.  4.  5.]
  [ 6.  7.  8.  9. 10.]]]


## 2.3 넘파이 배열의 크기와 데이터 형식 
넘파이 형식으로 된 배열을 보통 **넘파이 배열**이라고 부른다

In [ ]:
# 배열 크기 확인 -> 형태  -> 모양  (수학용어  ,행렬의 모양  shape of array)
print(넘파이형_1차원_배열.shape)
print(넘파이형_2차원_배열.shape)
print(넘파이형_3차원_배열.shape)

(5,)
(2, 5)
(2, 2, 5)


In [ ]:
# [보충] 배열 차원 확인 
print(넘파이형_1차원_배열.ndim)
print(넘파이형_2차원_배열.ndim)
print(넘파이형_3차원_배열.ndim)

1
2
3


In [ ]:
# 배열(을 이루고 있는 원소)의  데이터 형식 확인
print(넘파이형_1차원_배열.dtype)
print(넘파이형_2차원_배열.dtype)
print(넘파이형_3차원_배열.dtype)  # 각 원소의 데이터 형식이 float 형식이라는 점에 주목

# 신경망의 뉴론간의 연결을 가중치로 표현을 실수로 한다.   가중치는 신경세포간의 연결 신호 강도 비율 이다. 0.1234 -> 1234 64bit-> 16bit  메모리 1/4로 줄이면서 신경망을 구성할 수 있다.  

int64
int64
float64


int64는 정수형(64비트로 표현), float64는 소수점 수(실수형, 64비트로 표현)

In [ ]:
# 넘파이 부울 배열 
부울_배열 = np.array([True, False, True, 1, 0])
print(부울_배열)  #  (1 0 1 1 0)  -> 벡터 연산    -> 흑백영상이 있다고 하자 . 우편번호   숫자 영역 4로 설명  
print(부울_배열.shape)
print(부울_배열.dtype)

[1 0 1 1 0]
(5,)
int64


상삼각행렬, 하 삼각행렬등을 활용한 행렬 연산(특히 영상 처리)에 자주 쓰여요
그리고 행렬에서 특정 자료를 찾아 내거나 (인덱싱) 뽑아내거나  (슬라이싱) 해야 할 때 많이 사용한다. 

In [ ]:
# 넘파이 문자열 배열 
문자열_배열 = np.array([["우리는 A반", "우리는 B반"],
                        ["Class 1", "Class 2"]])

print(문자열_배열)
print(문자열_배열.shape)
print(문자열_배열.dtype)   # 문자열의 경우 데이터 형식이 상황에 따라 다르다.
                           # 하지만 의미가 없다.

[['우리는 A반' '우리는 B반']
 ['Class 1' 'Class 2']]
(2, 2)
<U7


## 2.4 특수한 배열 형성 
수치 처리를 하다 보면 0으로 채워진 배열이나 1로만 채워진 배열이나 수열로 이뤄진 배열이 필요할 때가 있다. 넘파이를 사용하면 이런 배열을 아주 쉽게 형성할 수 있다


### 2.4.1 전체 원소가 0인 배열 형성

In [ ]:
# 0으로만 이뤄진 1차원 배열
print(np.zeros(5))            # 따로 지정하지 않으면 float 형으로 형성된다.
#영행렬, 단위행렬(1로 채워진 행렬) 1차원 배열  = 벡터  /  2차원  행렬  /      3차원은 텐서 

[0. 0. 0. 0. 0.]


In [ ]:
# 0으로만 이뤄진 1차원 정수형 배열 
print(np.zeros(5, dtype=int)) # 데이터 형식을 따로 지정할 수 있다.

[0 0 0 0 0]


In [ ]:
# 0으로만 이뤄진 2차원 정수형 배열
print(np.zeros((2, 2), dtype=int))

[[0 0]
 [0 0]]


In [ ]:
# 0으로만 이뤄진 3차원 정수형 배열
print(np.zeros((2, 2, 2), dtype=int))

[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]


In [ ]:
# 참고로 메모리 크기까지도 지정할 수 있다. 
# 이에 대해서는 넘파이 공식 매뉴얼을 보자.
팔비트_배열 = np.zeros(5, dtype=np.ubyte) 
print(팔비트_배열)
print(팔비트_배열.dtype)

[0 0 0 0 0]
uint8


### 2.4.2 1로만 이뤄진 배열

In [ ]:
# 1로만 이뤄진 2차원 배열
print(np.ones((5, 3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### 2.4.3 수열로 이뤄진 배열 형성

In [ ]:
# 종료값만 지정하는 경우(시작 값은 0, 종료 값은 9)
print(np.arange(10))      #수열로  이루어진 배열 

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
 # 시작값과 종료값만 지정하는 경우
print(np.arange(2, 10))  

[2 3 4 5 6 7 8 9]


In [ ]:
# 시작값과 종료값과 단계값을 지정
print(np.arange(2, 10, 2))

[2 4 6 8]


## 2.5 넘파이 배열 연산
넘파이의 배열은 수학의 행렬(또는 텐서)을 표현하기 위한 것이므로 넘파이에서 배열 연산을 한다는 것은 **행렬 연산**을 한다는 것과 거의 같다




In [ ]:
# 행렬 덧셈을 위한 배열 준비
일 = np.ones((2, 2))
print(일)

[[1. 1.]
 [1. 1.]]


In [ ]:
# 배열 덧셈
이 = 일 + 일
print(이)

[[2. 2.]
 [2. 2.]]


In [ ]:
# 배열 뺄셈
영 = 일 - 일
print(영)

[[0. 0.]
 [0. 0.]]


In [ ]:
# 배열 곱셈 
사 = 이 * 이 
print(사)

 #곱셈  = 스칼라 곱
 

[[4. 4.]
 [4. 4.]]


In [ ]:
# 배열 나눗셈
이 = 사 / 이
print(이)

[[2. 2.]
 [2. 2.]]


In [ ]:
# 배열 나머지
나머지 = 사 % (사 - 일)
print(나머지)

[[1. 1.]
 [1. 1.]]


## 2.6 브로드캐스팅
기본적으로 크기가 같은 배열끼리 연산을 할 수 있고, 크기가 서로 다른 배열이라면 브로드캐스팅(broadcasting) 기능을 사용해 연산

In [ ]:
큰_일 = np.ones((2, 2))  # 배열의 크기 (2, 2) 
print(큰_일)


[[1. 1.]
 [1. 1.]]


In [ ]:
작은_일 = np.ones((2))   # 배열의 크기 (2,)
print(작은_일)

[1. 1.]


In [ ]:
print(큰_일 + 작은_일)  # 작은_일의 배열 크기가 (2, 2)로 조정되고
                        # 확장된 부분을 기존 배열 원소값으로 채운 후 연산

[[2. 2.]
 [2. 2.]]


## 2.7 스칼라 연산
행렬에 스칼라값을 가지고 연산할 수 있듯이 넘파이 배열에 스칼라 값을 가지고 연산

In [ ]:
print(사 * 2)

[[8. 8.]
 [8. 8.]]


In [ ]:
print(사 - 4)

[[0. 0.]
 [0. 0.]]


## 2.8 배열 인덱싱
넘파이 배열에서 인덱싱을 하는 방법은 파이썬에서 리스트 등을 대상으로 인덱싱을 하는 방법과 같다


### 2.8.1 일반적인 인덱싱

In [ ]:
# 1차원 배열 인덱싱
일차원_배열 = np.array([2, 4, 8, 10])
print(일차원_배열)

[ 2  4  8 10]


In [ ]:
print(일차원_배열[0])   # 스칼라 값이 나온다.

2


In [ ]:
데이터 = 일차원_배열[0]
type(데이터)

numpy.int64

In [ ]:
print(일차원_배열[:1])  # 행렬 값이 나온다.
print('\n')

[2]




In [ ]:
데이터2 = 일차원_배열[:1]
type(데이터2)

numpy.ndarray

In [ ]:
print(일차원_배열)

[ 2  4  8 10]


In [ ]:
print(일차원_배열[-1])  # 스칼라 값이 나온다.
print(일차원_배열[-1:]) # 행렬 값이 나온다.
print('\n')
print(일차원_배열[2:5])
print(일차원_배열[:3])
print(일차원_배열[1:])

10
[10]


[ 8 10]
[2 4 8]
[ 4  8 10]


In [ ]:
# 2차원 배열 인덱싱
이차원_배열 = np.array([[2, 4, 8, 10], [3, 5, 7, 9]]) 
print(이차원_배열[1, 1])  # 2행 2열 값이 출력된다.
print(이차원_배열[0, 3])  # 1행 4열 값이 출력된다.


5
10


In [ ]:
print(이차원_배열[:, 2])  # 각 행의 3열 값이 출력된다.
print(이차원_배열[1, :])  # 2행이 모두 출력된다.

[8 7]
[3 5 7 9]


### 2.8.2 [보충] 부울 인덱싱


In [ ]:
# 부울 값 기반 인덱싱에 쓸 배열들을 준비한다.
모수_배열 = np.array([1, 2, 3, 4, 5])
print(모수_배열)

[1 2 3 4 5]


In [ ]:
부울_배열_1 = np.array([True, False, True, False, True])
부울_배열_2 = np.array([1, 0, 1, 0, 1]) # 인덱싱을 할 때는 부울 값을 1, 0으로 표기하면 안 된다. 
                                        # 이것은 '정수 인덱싱'이라고 부르는 방법이기 때문이다. 
print(부울_배열_2)
print(모수_배열[부울_배열_1]) # 바른 방식이다. 
print(모수_배열[부울_배열_2]) # 문제가 생긴다. 
#~~~~~~! 중요하다  

[1 0 1 0 1]
[1 3 5]
[2 1 2 1 2]


### 2.8.3 [보충] 정수 인덱싱


In [ ]:
모수_배열 = np.array([1, 2, 3, 4, 5])
정수형_인덱스_배열 = np.array([0, 2, 3]) # 각 원소가 인덱스 값으로 쓰인다.

print(모수_배열[정수형_인덱스_배열])
# 출력을 해 보면 모수_배열의 0번째 원소(즉, 1), 
# 2번째 원소(즉, 3), 3번째 원소(즉, 4)가 출력되는 점을 볼 수 있다.

[1 3 4]


## 2.9 배열 슬라이싱
넘파이 배열 슬라이싱도 리스트 슬라이싱과 크게 다르지 않다

In [ ]:
이차원_배열 = np.array([[2, 4, 8, 10], [3, 5, 7, 9]]) 

print(이차원_배열[0, :]) # 첫 번째 행 전부
print(이차원_배열[:, 0]) # 첫 번째 열 전부
print(이차원_배열[0, 1:]) # 첫 번째 행의 두 번째 열부터 마지막 열까지 

[ 2  4  8 10]
[2 3]
[ 4  8 10]


# 3. 넘파이가 제공하는 메서드
.

## 3.1  난수 생성


In [ ]:
# 코드를 실행할 때마다 행렬 원소 값이 달라진다. 
난수_배열 = np.random.randn(5, 5)
print(난수_배열)

[[-0.22402771  0.02994763 -0.3090719  -1.07723534  0.67005179]
 [-1.43823945  1.08226749 -1.06658856 -0.07034148  0.91008925]
 [ 0.06774934  0.59451993  0.29065398 -0.35137354 -0.13938383]
 [-0.20942667  1.08792336 -0.3862425   0.52230953 -1.42966346]
 [-1.6546315   1.27932376  0.51654032 -2.14865187  1.29352108]]


## 3.2 기본 연산

In [ ]:
#  절댓값 구하기
절댓값_배열 = np.abs(난수_배열)
print(절댓값_배열)

[[0.22402771 0.02994763 0.3090719  1.07723534 0.67005179]
 [1.43823945 1.08226749 1.06658856 0.07034148 0.91008925]
 [0.06774934 0.59451993 0.29065398 0.35137354 0.13938383]
 [0.20942667 1.08792336 0.3862425  0.52230953 1.42966346]
 [1.6546315  1.27932376 0.51654032 2.14865187 1.29352108]]


In [ ]:
# 지수와 로그 연산
print(np.sqrt(절댓값_배열), '\n')   # 제곱근 구하기
print(np.square(절댓값_배열), '\n') # 제곱 구하기
print(np.exp(절댓값_배열), '\n')    # 자연 대수 구하기
print(np.log(절댓값_배열), '\n')    # 자연 로그 구하기
print(np.log10(절댓값_배열), '\n')  # 상용 로그 구하기
print(np.log2(절댓값_배열), '\n')   # 밑이 2인 로그 구하기

[[0.47331565 0.17305383 0.55594235 1.03789948 0.81856691]
 [1.19926621 1.04032086 1.03275774 0.26521969 0.95398598]
 [0.26028703 0.77105118 0.53912334 0.5927677  0.37334143]
 [0.45763158 1.04303565 0.62148411 0.72270985 1.19568535]
 [1.2863248  1.13107195 0.71870739 1.46582805 1.13733068]] 

[[5.01884135e-02 8.96860367e-04 9.55254397e-02 1.16043597e+00
  4.48969395e-01]
 [2.06853272e+00 1.17130291e+00 1.13761115e+00 4.94792445e-03
  8.28262451e-01]
 [4.58997262e-03 3.53453946e-01 8.44797345e-02 1.23463366e-01
  1.94278508e-02]
 [4.38595284e-02 1.18357723e+00 1.49183266e-01 2.72807242e-01
  2.04393761e+00]
 [2.73780541e+00 1.63666929e+00 2.66813901e-01 4.61670487e+00
  1.67319677e+00]] 

[[1.25110568 1.03040057 1.36216031 2.93654975 1.95433852]
 [4.21327161 2.95136415 2.9054508  1.07287449 2.48454428]
 [1.07009704 1.81216077 1.33730177 1.42101804 1.14956525]
 [1.23297095 2.96810398 1.47144145 1.68591683 4.17729313]
 [5.23115191 3.59420836 1.67621843 8.5732927  3.64560042]] 

[[-1.495985

In [ ]:
# 삼각함수 연산
새_난수_배열 = np.random.randn(2, 2)
print(np.cos(새_난수_배열), '\n') # 코사인 함수
print(np.sin(새_난수_배열), '\n')  # 사인 함수
print(np.tan(새_난수_배열), '\n')  # 탄젠트 함수

# 이 밖에도 sinh, cosh, tanh, arcsin, arccos, arctan, arcsinh, arccosh, arctanh가 구비되어 있다. 

[[-0.99922208  0.97213318]
 [ 0.50885574 -0.79905645]] 

[[ 0.03943654  0.23442926]
 [-0.86085181 -0.60125601]] 

[[-0.03946724  0.24114933]
 [-1.69174039  0.7524575 ]] 



## 3.3 행렬 간 연산

In [ ]:
# 연산에 쓸 정수 행렬 두 개를 생성한다.
행렬_1 = np.random.randint(5, size=(5, 5))  # 0 ~ 4 사이 난수 생성     균등 분포  (최대값 , 사이즈 )
행렬_2 = np.random.randint(5, size=(5, 5)) # 정수형 균등 분포를 형성한다.  

print(행렬_1)
print('\n')
print(행렬_2)

[[4 0 4 4 4]
 [2 0 3 1 0]
 [3 4 4 4 1]
 [3 1 2 2 4]
 [0 0 0 2 2]]


[[3 2 0 1 1]
 [2 4 2 3 3]
 [4 2 4 2 2]
 [4 0 0 3 1]
 [2 4 4 1 2]]


In [ ]:
# 행렬 간 사칙연산
print(np.add(행렬_1, 행렬_2), '\n')       # 덧셈
print(np.subtract(행렬_1, 행렬_2), '\n')  # 뺄셈
print(np.multiply(행렬_1, 행렬_2), '\n')  # 곱셈  


[[7 2 4 5 5]
 [4 4 5 4 3]
 [7 6 8 6 3]
 [7 1 2 5 5]
 [2 4 4 3 4]] 

[[ 1 -2  4  3  3]
 [ 0 -4  1 -2 -3]
 [-1  2  0  2 -1]
 [-1  1  2 -1  3]
 [-2 -4 -4  1  0]] 

[[12  0  0  4  4]
 [ 4  0  6  3  0]
 [12  8 16  8  2]
 [12  0  0  6  4]
 [ 0  0  0  2  4]] 



In [ ]:
# 행렬 간에 나눗셈을 할 때의 문제
print(np.divide(행렬_1, 행렬_2))    # 나눗셈   ㅠ infinit  = 무한대       # nan    a number   = 수가 아니다.  

#중간에  0으로 나눈값이 존재 한다.  

[[1.33333333 0.                inf 4.         4.        ]
 [1.         0.         1.5        0.33333333 0.        ]
 [0.75       2.         1.         2.         0.5       ]
 [0.75              inf        inf 0.66666667 4.        ]
 [0.         0.         0.         2.         1.        ]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


행렬 간에 나눗셈을 할 때는 0으로 나누는 경우 등이 생길 수 있다

In [ ]:
# 행렬 간의 최댓값/최솟값 구하기 
print(np.maximum(행렬_1, 행렬_2), '\n')    # 최댓값
print(np.minimum(행렬_1, 행렬_2), '\n')    # 최솟값

[[4 2 4 4 4]
 [2 4 3 3 3]
 [4 4 4 4 2]
 [4 1 2 3 4]
 [2 4 4 2 2]] 

[[3 0 0 1 1]
 [2 0 2 1 0]
 [3 2 4 2 1]
 [3 0 0 2 1]
 [0 0 0 1 2]] 



## 3.4 통계 연산
넘파이를 사용하면 행렬에 대한 각종 **통계량**(stats)을 쉽게 알 수 있다

머신러닝, 딥러닝  = 수리통계 , 통계학 , 수학  
내장  =  embedding  
Guassian model   = 가우스 모형  , 가우스 혼합 



In [ ]:
# 연산에 쓸 정수 행렬 한 개를 생성한다.
행렬 = np.random.randint(20, size=(5, 5))  # 0 ~ 19 사이 난수 생성
print(행렬)

[[14 11  6  9  6]
 [ 8  9 13 15  6]
 [ 6 15  7  1  7]
 [ 3 12  9  4 18]
 [18 10 17  9  4]]


In [ ]:
# 성분별 합계 구하기
print(np.sum(행렬), '\n')           # 전체 성분의 합
print(np.sum(행렬, axis = 0), '\n') # 행 성분의 합
print(np.sum(행렬, axis = 1), '\n') # 열 성분의 합

262 

[58 22 80 59 43] 

[45 54 54 51 58] 



In [ ]:
# 평균, 표준편차, 분산, 중앙값 계산하기   :  탐색적 데이터 분석시 사용 
print(np.mean(행렬), '\n')    # 전체 성분의 평균 
print(np.var(행렬), '\n')     # 전체 성분의 분산
print(np.std(행렬), '\n')     # 전체 성분의 표준편차
print(np.median(행렬), '\n')  # 전체 성분의 중위수

10.48 

39.6896 

6.299968253888268 

11.0 



In [ ]:
# 사분위수 구하기
print(np.percentile(행렬, 0), '\n') # 전체 성분의 최솟값
print(np.percentile(행렬, 25), '\n') # 전체 성분의 1/4분위 위치 값 
print(np.percentile(행렬, 50), '\n') # 전체 성분의 2/4분위 위치 값 
print(np.percentile(행렬, 75), '\n') # 전체 성분의 3/4분위 위치 값 
print(np.percentile(행렬, 100), '\n') # 전체 성분의 4/4분위 위치 값  = 최댓값

0.0 

5.0 

11.0 

16.0 

19.0 



In [ ]:
# 최댓값, 최솟값 구하기
print(np.max(행렬), '\n') # 전체 성분의 최댓값
print(np.min(행렬), '\n') # 전체 성분의 최솟값

19 

0 



## 3.5 난수 처리


### 3.5.1 시드 값 정하기
시드(seed)란 우리 말로 하면 '씨앗'으로 번역될 수 있는 말로, 여러 차례에 걸쳐 난수를 생성할 때 매번 같은 난수가 생성될 수 있도록 하기 위한 시촛값에 해당 이 값을 정해두면 코드가 새로 실행될 때마다 난수가 바뀌지 않기 때문에, 코드가 항상 동일한 결과를 낼 수 있게 할 수 있다. 즉, **코드의 재현성**에 필수인 기능이다

In [ ]:
# 시드를 정하지 않고 난수를 거듭 발생시키는 경우 
# 매번 다른 결과가 나온다. 
print(np.random.rand(5), '\n')
print(np.random.rand(5), '\n')

[0.44345544 0.35933643 0.12991391 0.22760695 0.5545243 ] 

[0.72574494 0.59560351 0.47267767 0.68898728 0.99557161] 



In [ ]:
# 똑같은 시드 값을 정해 난수를 거듭 발생시키는 경우
# 매번 같은 값이 나온다.  모의 데이터 실험시 매번 모의 데이터가 같아야 비교를 한다.  
np.random.seed(0)  # 시드 값을 정할 때는 0 이상인 정수로 지정한다.
print(np.random.rand(5), '\n')

np.random.seed(0)
print(np.random.rand(5), '\n')


[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ] 

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ] 



### 3.5.2 난수 생성


#### 3.5.2.1 균일 분포 배열 형성

In [ ]:
# 크기가 5인 일차원 균일 배열(즉, 벡터 또는 일차 텐서) 형성
# 이때 각 성분의 범위는 0 ~ 1
일차원_균일분포_배열 = np.random.rand(5)  
print(일차원_균일분포_배열)
print('\n')


[0.287991   0.38346223 0.74916984 0.87845219 0.10286336]




In [ ]:
# 크기가 5 X 5인 이차원 균일분포 배열(즉, 행렬 또는 이차 텐서) 형성
# 이때 각 성분의 범위는 0 ~ 1
이차원_균일분포_배열 = np.random.rand(5, 5)  #균일 분포   randn() -> normal  =정규분포  
print(이차원_균일분포_배열)

[[0.09237389 0.35404666 0.55181626 0.03362509 0.96896177]
 [0.32099724 0.22126269 0.1412639  0.09725993 0.98404224]
 [0.26034093 0.53702252 0.44792617 0.09956909 0.35231166]
 [0.46924917 0.84114013 0.90464774 0.03755938 0.50831545]
 [0.16684751 0.77905102 0.8649333  0.41139672 0.13997259]]


In [ ]:
# 각 성분 값이 정수로 된 2차원 균일 분포 배열 형성
print(np.random.randint(20, size = 20), '\n')  # 0 ~ 19 사이 정수 균일분포 형성
print(np.random.randint(20, 40, size = 20), '\n') # 20 ~ 39 사이 정수 균일분포 형성
print(np.random.randint(20, 40, size = (4, 5)), '\n') # 20 ~ 39 사이 2차원 균일 분포 형성

[16 16  3 17 10  9 12 13  6  6  7  8 13  7 16 15  8  3  6 17] 

[27 22 36 38 33 24 24 32 37 21 25 21 39 39 27 29 37 29 20 39] 

[[24 37 36 23 30]
 [21 24 24 36 36]
 [35 30 33 28 31]
 [26 29 35 23 39]] 



In [ ]:
# 각 성분 값이 정수로 된 3차원 균일 분포 배열 형성
print(np.random.randint(10, size = (2,3,4)))

[[[9 5 5 1]
  [7 8 6 4]
  [7 3 5 3]]

 [[6 4 7 3]
  [0 5 9 3]
  [7 5 5 8]]]


In [ ]:
# 표준정규분포(기댓값이 0, 표준편차가 1인 분포)를 따르는 1차원 배열 형성 : 표준분포로 초기화하게 되면 인공지능이 필용하다.  
일차원_표준정규분포_배열 = np.random.randn(5)  # 크기가 5인 벡터
print(일차원_표준정규분포_배열)


[-0.89989113  0.12924181  0.97969276  0.32837496  0.48707415]


In [ ]:
# 표준정규분포(기댓값이 0, 표준편차가 1인 분포)를 따르는 2차원 배열 형성
이차원_표준정규분포_배열 = np.random.randn(5, 5)  # 크기가 5X5인 행렬 형성
print(이차원_표준정규분포_배열)

[[ 0.14484156 -0.0856099   0.7105399   0.93095988  0.87507402]
 [-0.71156531 -0.36120904 -2.10924743 -1.09376775  1.2045055 ]
 [ 0.11108051  1.96099802  0.39459838 -0.82712929  0.22490418]
 [-0.15302329 -0.24072956  0.08158307  1.23816955  2.18377828]
 [ 0.19056415 -0.49816695  0.04751241  1.44832909  0.42822114]]


### 3.5.3 데이터 임의표본추출
표본추출(sampling)이라는 말을 컴퓨터과학을 포함해 다양한 이과/공과 계열 학문에서는 **샘플링**이라고 부르는 경우도 많지만, 향후 인공지능 구현 시에 통계학에서 유래한 개념들이 많이 쓰이므로(딥러닝도 마찬가지) 앞으로 **표본추출**이나 **표집**이라고 부른다(어감에 차이가 있지만 무시). **임의표본추출**(random sampling), 즉 **임의표집**이란 **모집단**(population)에서 아무렇게나 **표본**(sample)을 선택해 **추출**(sampling)한다는 말

In [ ]:
# 일차원 표본추출 배열 형성
표본추출_배열 = np.random.choice(10, 5)  # 모집단은 0~9, 벡터 크기는 5
print(표본추출_배열)

[2 5 4 9 1]


In [ ]:
# 이차원 표본추출 배열 형성
표본추출_배열 = np.random.choice(10, (5, 5))  # 모집단은 0~9, 행렬 크기는 3X5
print(표본추출_배열)

[[5 9 4 5 7]
 [4 4 2 2 1]
 [3 0 1 9 1]
 [6 9 8 6 3]
 [0 7 3 2 5]]


In [ ]:
# [참고] flatten() 메서드를 사용해 행렬을 벡터로 만들기  = 시계열  
print(표본추출_배열.flatten()) # 행렬  -> 벡터       평탄화     flattening  한줄로 늘여 뜨린다. 

[5 9 4 5 7 4 4 2 2 1 3 0 1 9 1 6 9 8 6 3 0 7 3 2 5]


In [ ]:
# 기존 행렬을 모집단으로 사용하는 경우
# ***위에 출력되지 않은 값이 전혀 나오지 않는다는 점을 잘 살펴보자.***
새_표본추출_배열 = np.random.choice(표본추출_배열.flatten(), (3, 5))  # 모집단은 0~9, 행렬 크기는 3X5
print(새_표본추출_배열)

[[2 6 1 5 0]
 [2 3 2 3 4]
 [3 2 8 0 5]]


In [ ]:
# 각 데이터의 선택 확률을 지정해 표본추출해서 배열을 형성하기
# 모집단은 0~2, 행렬 크기는 10 X 10
# p(0)=0.0, p(1)=0.9, p(2)=0.1
표본추출_배열 = np.random.choice(3, size=(10, 10), p=[0.1, 0.8, 0.1])    #0이 뽑힐 확률 10%   1이 출력될 확률은 80%  2가 출력될 확률은 10%
print(표본추출_배열)                       

[[1 1 0 1 1 1 2 1 2 1]
 [1 1 1 1 1 1 1 1 1 0]
 [1 0 2 1 1 1 1 1 1 1]
 [2 1 1 1 1 1 1 0 1 1]
 [1 1 2 1 1 0 1 1 1 1]
 [1 1 1 1 1 0 0 2 1 1]
 [1 1 2 1 1 0 1 1 1 1]
 [1 0 2 1 1 0 2 0 1 1]
 [1 1 1 1 1 1 1 1 1 2]
 [1 1 1 2 1 1 1 2 0 1]]


출력 결과를 보면 0이 표본추출되지 않고 주로 1이 표본추출되며, 간간이 2가 표본추출된 것을 볼 수 있습니다.

## 3.6 정수 데이터 분석
우리는 앞에서 정수 성분으로 이뤄진 분포를 형성해 본 적이 있다. 그런데 성분의 개수가 굉장히 많다면 해당 분포에서 다시 데이터를 추출해 탐색해 보는 일이 필요

파이썬  -> 넘파이 . 파이썬 ->머신러닝/ 딥러닝  -> 머신 -> 딥러닝 


In [ ]:
# 크기가 5 X 95인 2차원 배열 형성
새_분포 = np.random.randint(100, size=(5, 95))  # 모집단 0~ 99  에서 중복 추출 후 새로운 분포를 만들자 정수형 균일 분포 , 복원 추출 
print(새_분포)

[[ 3 53 37  7 80 75 11  2 54  5 17 78  5 78 81 30 98  3  0 93 44 44 61  0
  17 29 91 34 59 21 63 94 17 38 79  1 15 86 17 53 22 77 47 66 11  9 40 54
  51 47  4 10  6 44 72  8 72 18  2 69 93 29 27 17 58 11 49 72 88  3 11 57
  50 15 57  3 60 39 85 29 53 67 56 75 79 45 90 79 97 11  5 30 58 68 59]
 [32 37 43 60 45 29 27 27 29 72 75 97 78 38 11 74 89 32 50 40 70 30 22 75
  35 84 68 63  4 49 29 63 61 91 83 90 26 73 50 95 94 17 71 56 35 73 92 47
  48 71 67 71 62 72 37  5 97 55 92 46 38 49  8 65 66 62 16 61 66 11 31 10
  20 14 52 71 29  5 14 79 51 32 23 91  6 73 65 75 87 70 40 60 36 12 35]
 [62 69 62 58 76 18  0  1 84 77 90 21 78 13 67 17  5 26 63 27 41 13 45 48
  56 58 17 86 95 89 92 77  7 26 17 68 43 47 94 92 72 58 27  6  7 53 26 75
  37 93 49 20 93 56 61 55 92 23 57  9  0 19 71 50 38 67 30 37 56  5 59 80
  90 61 31 70 89 75 17 31 31 84 90 39 50 74 38 68 39 79 13 35 11 75 54]
 [36 82 75 51 34 58 80 28  9  8 17 92 25 94 59 94 59 58 18 12  1 27 10 67
  61 16 27  6  0  7 25 67 59 36 44 85 72 38 

In [ ]:
# 고윳값(unique value, 중복되지 않은 값) 찾기 
# 주의: 차원축소 방법에서 말하는 고윳값(eigenvalue)과 혼동하지 말 것
성분_값, 성분별_개수 = np.unique(새_분포, return_counts=True)
print(성분_값)
print(성분별_개수) # 자연어 처리시에  추출 중복되지 않은 어절 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 97 98]
[ 8  4  3  5  4  9  9  4  3  3  6  8  4  7  3  2  8 12  5  4  3  5  3  4
  4  6  8  1  9  6  7  3  1  4  4  7  9  8  5  4  3  2  2  7  5  2  8  4
  6  5  4  2  6  4  4  5  4  7  7  5  8  6  6  3  4  7  6  4  6  5 10  5
  4 10  5  3  4  5  5  1  1  2  5  2  3  1  2  3  7  5  6  4  9  5  7  2]


In [ ]:
# 성분별 개수를 알고 싶지 않은 경우에는 return_counts=False라고 지정하거나
# return_counts를 지운다. 
성분_값 = np.unique(새_분포)
print(성분_값)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 97 98]


In [ ]:
# [참고 코드] 성분 값과 성분별 개수를 튜플 형태로 짝을 짓기
# list 함수를 사용해 행렬(넘파이 배열)을 리스트로 캐스팅하고
# zip 함수를 사용해 두 리스트를 튜플 형태로 짝 지은 다음에
# 다시 리스트 형태로 만들어(파이썬 3에서는 이렇게 한 단계 더 거쳐야 함)
# 출력한다.
print(list(zip(list(성분_값), list(성분별_개수)))) 

[(0, 8), (1, 4), (2, 3), (3, 5), (4, 4), (5, 9), (6, 9), (7, 4), (8, 3), (9, 3), (10, 6), (11, 8), (12, 4), (13, 7), (14, 3), (15, 2), (16, 8), (17, 12), (18, 5), (19, 4), (20, 3), (21, 5), (22, 3), (23, 4), (25, 4), (26, 6), (27, 8), (28, 1), (29, 9), (30, 6), (31, 7), (32, 3), (33, 1), (34, 4), (35, 4), (36, 7), (37, 9), (38, 8), (39, 5), (40, 4), (41, 3), (42, 2), (43, 2), (44, 7), (45, 5), (46, 2), (47, 8), (48, 4), (49, 6), (50, 5), (51, 4), (52, 2), (53, 6), (54, 4), (55, 4), (56, 5), (57, 4), (58, 7), (59, 7), (60, 5), (61, 8), (62, 6), (63, 6), (65, 3), (66, 4), (67, 7), (68, 6), (69, 4), (70, 6), (71, 5), (72, 10), (73, 5), (74, 4), (75, 10), (76, 5), (77, 3), (78, 4), (79, 5), (80, 5), (81, 1), (82, 1), (83, 2), (84, 5), (85, 2), (86, 3), (87, 1), (88, 2), (89, 3), (90, 7), (91, 5), (92, 6), (93, 4), (94, 9), (95, 5), (97, 7), (98, 2)]


## 3.7 데이터 섞기
수치 처리를 하다 보면 난수 형성만으로는 충분하지 않을 때가 있다. 우리가 만든 데이터나 난수를 아무렇게나 섞어야 할 때가 있다. 넘파이의 numpy.random.shuffle()을 사용하면 이렇게 할 수 있다

In [ ]:
# 1차원 배열 섞기

# 먼저 1차원 배열을 만들어 보자. 
배열 = np.arange(10)
print(배열, '\n')

# 그리고 이 행렬을 섞어 보자.
np.random.shuffle(배열)
print(배열, '\n')

[0 1 2 3 4 5 6 7 8 9] 

[0 4 5 1 3 2 9 8 6 7] 



In [ ]:
# 2차원 이상인 배열 섞기 
배열 = np.arange(25).reshape(5, 5)
print(배열, '\n')

np.random.shuffle(배열)
print(배열, '\n')

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]] 

[[10 11 12 13 14]
 [20 21 22 23 24]
 [ 0  1  2  3  4]
 [15 16 17 18 19]
 [ 5  6  7  8  9]] 



출력 결과를 통해서 2차원 이상인 행렬의 경우에는 첫 번째 축(여기서는 행)에 대해서만 무작위 섞기(임의 재편성)가 진행된다는 점을 알 수 있다. 

In [ ]:
# [참고 코드] 2차원 이상인 배열에 대해서 그 성분을 온전히 다 섞어야 한다면?
# 이럴 때는 배열을 1차원으로 만들어(평탄화를 해서) 섞은 다음에 
# 다시 3차원 꼴로 편성하는 요령을 발휘하면 된다.
일차원_배열 = 배열.flatten()
print(일차원_배열, '\n')

np.random.shuffle(일차원_배열)
print(일차원_배열, '\n')

이차원_배열 = 일차원_배열.reshape(5, 5)
print(이차원_배열, '\n')

[10 11 12 13 14 20 21 22 23 24  0  1  2  3  4 15 16 17 18 19  5  6  7  8
  9] 

[ 1 10  2 14  7 17  8 23 15  6  0 20 22  9 18 19  3 16  4 21 11 12  5 24
 13] 

[[ 1 10  2 14  7]
 [17  8 23 15  6]
 [ 0 20 22  9 18]
 [19  3 16  4 21]
 [11 12  5 24 13]] 



## 3.8 기타 연산 

In [ ]:
# 그 밖의 연산에 쓸 새 난수를 생성해 두자. 
새_난수_배열 = np.random.randn(3, 3)
print(새_난수_배열)

[[-0.85491288 -0.55919488  0.02285489]
 [-0.93630383 -0.20387702  1.12518905]
 [ 0.56205436 -0.34517926  0.01140603]]


In [ ]:
# 각 성분의 부호 알아내기
# 음수는 -1, 영은 0, 양수는 1로 나옴
print(np.sign(새_난수_배열))  

[[-1. -1.  1.]
 [-1. -1.  1.]
 [ 1. -1.  1.]]


In [ ]:
# 올림과 내림 
print(np.ceil(새_난수_배열), '\n')    # 소수점 이하 첫 번째 자리에서 올림
print(np.floor(새_난수_배열), '\n')   # 소수점 이하 첫 번쨰 자리에서 내림

[[-0. -0.  1.]
 [-0. -0.  2.]
 [ 1. -0.  1.]] 

[[-1. -1.  0.]
 [-1. -1.  1.]
 [ 0. -1.  0.]] 



In [ ]:
# 성분이 NaN(수치가 아님)인 경우 알아내기

# 먼저 NaN이 나올 만한 연산을 한다.
print(np.sqrt(새_난수_배열), '\n') 

# NaN 성분을 알아낸다. 
print(np.isnan(np.sqrt(새_난수_배열)), '\n')

[[       nan        nan 0.15117834]
 [       nan        nan 1.06074929]
 [0.74970285        nan 0.10679901]] 

[[ True  True False]
 [ True  True False]
 [False  True False]] 



/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in sqrt
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: RuntimeWarning: invalid value encountered in sqrt
  import sys


https://numpy.org/devdocs/index.html