# Numpy ndarray 개요

In [1]:
#import

import numpy as np

In [2]:
array1 = np.array([1,2,3])
print('array1 type : ', type(array1))
print('array1 array 형태 : ', array1.shape) 
print(array1)
#1차원 array로 3개의 데이터를 가지고 있다.

array2 = np.array([[1,2,3],
                   [2,3,4]])
print('array2 type : ', type(array2))
print('array2 array 형태 : ', array2.shape)
print(array2)
#2차원 array로 2개의 ROW와 3개의 Colum의 데이터로 가지고 있다.

array3 = np.array([[1,2,3]])
print('array3 type : ', type(array3))
print('array3 array 형태 : ', array3.shape)
print(array3)
#2차원 array로 1개의 ROW와 3개의 Colum의 데이터로 가지고 있다.

array1 type :  <class 'numpy.ndarray'>
array1 array 형태 :  (3,)
[1 2 3]
array2 type :  <class 'numpy.ndarray'>
array2 array 형태 :  (2, 3)
[[1 2 3]
 [2 3 4]]
array3 type :  <class 'numpy.ndarray'>
array3 array 형태 :  (1, 3)
[[1 2 3]]


In [3]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


In [4]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)
#list를 int형으로 자동으로 변환

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [5]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype) #int형이 유니코드 문자열 값으로 변환되었다.

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype) #int형이 float64로 변환되었다.
#만약 다른 데이터 유형이 섞여있는 리스트를 ndarray로 변경할 시
#데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용한다.

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [6]:
#ndarray 내 데이터값의 타입 변경은 astype() 메서드를 이용한다.
#메모리를 절약해야할 때 이용된다.
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1= array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2= array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [7]:
sequence_array = np.arange(10) #default 함수 인자는 stop값이며 0부터 stop값인 10에서 -1까지의 연속 숫자 값을 배열에 넣는다.
sequence_array2 = np.array(range(10))
sequence_array3 = np.arange(1,11) #arange(x, y) = x이상부터 y미만까지의 값을 배열에 넣는다.
print(sequence_array)
print(sequence_array2)
print(sequence_array3)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
int32 (10,)


In [8]:
zero_array = np.zeros((3, 2),dtype = 'int32') #dtype을 지정하지 않으면 float64형태로 저장한다.
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3, 2)) #dtype을 지정하지 않으면 float64형태로 저장한다.
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [9]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5) #ndarray를 특정 차원 및 크기로 변환한다.
print('array2:\n',array2)

array3 = array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [10]:
array1.reshape(4,3) #단, 지정된 사이즈로 변경이 불가능하면 오류가 발생한다.

ValueError: cannot reshape array of size 10 into shape (4,3)

In [11]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5) #인자를 -1로 넣으면 원래 ndarray와 호환되는 새로운 shape로 변환해준다.
print('array2 shape:',array2.shape)

array3 = array1.reshape(5,-1)
print('array3 shape:',array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
array3 shape: (5, 2)


In [12]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4) #물론 -1을 사용하더라고 호환될 수 없는 형태는 반환할 수 없다.

ValueError: cannot reshape array of size 10 into shape (4)

In [13]:
array1 = np.arange(12)
print(array1)

array2 = array1.reshape(2, 2, -1) #3차원으로 변환
print('array2 shape:',array2.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
array2 shape: (2, 2, 3)


In [14]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

#reshape(-1,1)이 자주 사용되는 이유
#여러개의 넘파이 ndarray는 stack이나 concat으로 결합될 때 각각의 ndarray의 형태를 통일해 유용하게 사용된다.


array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]
array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)
array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


In [15]:
#그럼 stack과 concat이 뭘까?
#두개의 ndarray를 합치는 기능은 동일하나 stack이 더 제약이 많다.
a = np.array([[1, 2], [3, 4]]) # a.shape=(2, 2)
b = np.array([[5, 6]]) # b.shape=(2, 1)

In [16]:
print(np.concatenate((a, b), axis = 0)) # concatenate 함수는 합칠 axis를 제외한 shape 값을 제외하고 일치하면 가능하다.

[[1 2]
 [3 4]
 [5 6]]


In [17]:
print(np.stack((a, b), axis=0)) # stack 함수는 합치려는 배열들의 shape가 전부 동일해야합니다. 

ValueError: all input arrays must have the same shape

In [18]:
a = np.array([[1, 2], [3, 4]]) # a.shape=(2, 2)
b = np.array([[5, 6], [7, 8]]) # b.shape=(2, 2)

In [19]:
print(np.concatenate((a, b), axis = 0)) #shape = (4, 2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [20]:
print(np.stack((a, b), axis=0)) #shape = (2, 2, 2)
#stack 함수는 지정한 axis를 완전히 새로운 axis로 생각하게 됩니다.

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Indexing

- 단일값 추출

##### 단일값 추출을 수행하면 데이터를 가져온다.
##### 즉, ndarray 타입이 아닌 데이터 그 자체를 반환한다.

In [21]:
# 1에서 부터 9 까지의 1차원 ndarray 생성 
array1 = np.arange(start=1, stop=10)
print('array1:',array1)

# index는 0 부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값을 의미
value = array1[2]
print('value:',value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [22]:
print('맨 뒤의 값:',array1[-1], ', 맨 뒤에서 두번째 값:',array1[-2])

맨 뒤의 값: 9 , 맨 뒤에서 두번째 값: 8


In [23]:
array1[0] = 9
array1[8] = 0
print('array1:',array1)

array1: [9 2 3 4 5 6 7 8 0]


In [24]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d)

print('(row=0,col=0) index 가리키는 값:', array2d[0,0] )
print('(row=0,col=1) index 가리키는 값:', array2d[0,1] ) # [row=0, col=1] == [axis 0 = 0, axis 1 = 1]
print('(row=1,col=0) index 가리키는 값:', array2d[1,0] )
print('(row=2,col=2) index 가리키는 값:', array2d[2,2] )

#axis 0 = row(행)
#axis 1 = col(열)
#axis 2 = depth(높이)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0,col=0) index 가리키는 값: 1
(row=0,col=1) index 가리키는 값: 2
(row=1,col=0) index 가리키는 값: 4
(row=2,col=2) index 가리키는 값: 9


<span style="font-size:30px">- Slicing</span>

### Slicing 문법 
#### [x:y] = x인덱스부터 y-1 인덱스까지의 데이터를 추출한다.

##### 단일값 추출을 제외한 슬라이싱, 팬시 인덱싱, 불린 인덱싱으로 추출된 데이터 세트는 모두 ndarray 타입이다.

In [25]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


1. [x:y] 중 x값을 생략하면 자동으로 맨 처음 인덱스인 0으로 간주한다.
2. [x:y] 중 y값을 생략하면 자동으로 맨 마지막 인덱스로 간주한다.
3. [x:y] 중 x와 y를 모두 생략하면 자동으로 맨 처음/맨 마지막 인덱스로 간주한다 -> 모든 인덱스 값 추출

In [26]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


## 2차원 배열 슬라이싱

In [27]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [30]:
#2차원 ndarray에서 뒤에 오는 인덱스를 없애면 1차원 ndarray를 반환합니다.
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape )

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


<span style="font-size:30px">- Fancy Indexing</span>

- 리스트나 ndarray로 인덱스 집합을 지정하면 해당 위치의 인덱스에 해당하는 ndarray를 반환하는 인덱싱 방식입니다.
- 사실 Fancy를 붙일만큼 특별하진않다.

In [32]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)

array3 = array2d[[0,1], 2]
print('array2d[[0,1], 2] => ',array3.tolist())

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] => ',array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] => ',array5.tolist())

array2d[[0,1], 2] =>  [3, 6]
array2d[[0,1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


<span style="font-size:30px">- Boolean Indexing</span>

- 조건 필터링과 검색을 동시에 할 수 있기 때문에 매우 자주 사용되는 인덱싱 방식입니다.
- 불린 인덱싱은 ndarray의 인덱스를 지정하는 [ ]내에 조건문을 그대로 기재하기만 하면 됩니다.

In [33]:
array1d = np.arange(start=1, stop=10)
# [ ] 안에 array1d > 5 Boolean indexing을 적용 
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값 :', array3)

array1d > 5 불린 인덱싱 결과 값 : [6 7 8 9]


In [34]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

단지 ndarray 객체에 조건식만 붙였을 뿐인데 False, True로 이뤄진 ndarray 객체를 반환했다.

조건으로 반환된 이 ndarray 객체를 인덱싱을 지정하는 [ ] 내에 입력하면 False값은 무시하고 True 값이 있는 위치 인덱스 값으로 자동 변환해 해당하는 인덱스 위치의 데이터만 반환하게 됩니다.

In [35]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과 :', array3)

불린 인덱스로 필터링 결과 : [6 7 8 9]


In [36]:
indexes = np.array([5,6,7,8])
array4 = array1d[ indexes ]
print('일반 인덱스로 필터링 결과 :',array4)

일반 인덱스로 필터링 결과 : [6 7 8 9]


# 행렬의 정렬 – sort( )와 argsort( )

<span style="font-size:30px">- np.sort()</span>
- 넘파이에서 sort()를 호출하는 방식
- 원 행렬을 그대로 유지한 채 원 행렬의 정렬된 행렬을 반환한다.

<span style="font-size:30px">- ndarray.srot</span>
- 행렬 자체에서 sort()를 호출하는 방식
- 원 행렬 자체를 정렬한 형태로 변환하며 반환값은 NONE이다.

In [42]:
org_array = np.array([ 3, 1, 9, 5])
print('원본 행렬 :', org_array)

# np.sort( )로 정렬 
sort_array1 = np.sort(org_array)
print ('np.sort( ) 호출 후 반환된 정렬 행렬:', sort_array1)
print('np.sort( ) 호출 후 원본 행렬:', org_array)

# ndarray.sort( )로 정렬
sort_array2 = org_array.sort()
print('org_array.sort( ) 호출 후 반환된 행렬:', sort_array2)
print('org_array.sort( ) 호출 후 원본 행렬:', org_array)

원본 행렬 : [3 1 9 5]
np.sort( ) 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort( ) 호출 후 원본 행렬: [3 1 9 5]
org_array.sort( ) 호출 후 반환된 행렬: None
org_array.sort( ) 호출 후 원본 행렬: [1 3 5 9]


In [44]:
#내림차순 정렬 - [::-1]
sort_array1_desc = np.sort(org_array)[::-1]
print ('내림차순으로 정렬:', sort_array1_desc) 

내림차순으로 정렬: [9 5 3 1]


<span style="font-size:20px">2차원 배열 정렬</span>

In [51]:
array2d = np.array([[8, 12], 
                   [7, 1 ]])

sort_array2d_axis0 = np.sort(array2d, axis=0)
print('로우 방향으로 정렬:\n', sort_array2d_axis0, '\n')

sort_array2d_axis1 = np.sort(array2d, axis=1)
print('컬럼 방향으로 정렬:\n', sort_array2d_axis1)

로우 방향으로 정렬:
 [[ 7  1]
 [ 8 12]] 

컬럼 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


<span style="font-size:20px">정렬 행렬의 인덱스 반환 np.argsort()</span>
- 정렬 행렬의 원본 행렬 인덱스를 ndarray 형으로 반환한다.

In [52]:
org_array = np.array([ 3, 1, 9, 5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_indices)

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [53]:
org_array = np.array([ 3, 1, 9, 5]) 
sort_indices_desc = np.argsort(org_array)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_indices_desc)

행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


- ndarray는 RDBMS의 TABLE 칼럼이나 뒤에 소개할 판다스 DataFrame 칼럼과 같은 메타 데이터를 가질 수 없다.

In [54]:
import numpy as np

name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array= np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print('성적 오름차순 정렬 시 score_array의 인덱스:', sort_indices_asc)
print('성적 오름차순으로 name_array의 이름 출력:', name_array[sort_indices_asc])

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순으로 name_array의 이름 출력: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


<span style="font-size:20px">선형대수 연산 – 행렬 내적과 전치 행렬 구하기</span>
- 행렬 내적(행렬 곱)

    조건 : 왼쪽 행렬의 열 개수와 오른쪽 행렬의 행 개수가 동일해야 내적 연산이 가능합니다.
    
    결과 : (왼쪽 행렬의 행 개수, 오른쪽 행렬의 열 개수)의 shape를 가진 행렬이 반환된다.

In [56]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

dot_product = np.dot(A, B)
print('행렬 내적 결과:\n', dot_product)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


- 전치 행렬

    행과 열의 위치를 교환한 원소로 구성한 행렬을 전치 행렬이라고 합니다.

In [57]:
A = np.array([[1, 2],
              [3, 4]])
transpose_mat = np.transpose(A)
print('A의 전치 행렬:\n', transpose_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]


In [58]:
B = np.array([[1, 2],
              [3, 4],
              [5, 6]])
transpose_mat = np.transpose(B)
print('B의 전치 행렬:\n', transpose_mat)

B의 전치 행렬:
 [[1 3 5]
 [2 4 6]]
