# Numpy ndarray 개요

In [1]:
#import

import numpy as np

In [2]:
array1 = np.array([1,2,3])
print('array1 type : ', type(array1))
print('array1 array 형태 : ', array1.shape) 
print(array1)
#1차원 array로 3개의 데이터를 가지고 있다.

array2 = np.array([[1,2,3],
                   [2,3,4]])
print('array2 type : ', type(array2))
print('array2 array 형태 : ', array2.shape)
print(array2)
#2차원 array로 2개의 ROW와 3개의 Colum의 데이터로 가지고 있다.

array3 = np.array([[1,2,3]])
print('array3 type : ', type(array3))
print('array3 array 형태 : ', array3.shape)
print(array3)
#2차원 array로 1개의 ROW와 3개의 Colum의 데이터로 가지고 있다.

array1 type :  <class 'numpy.ndarray'>
array1 array 형태 :  (3,)
[1 2 3]
array2 type :  <class 'numpy.ndarray'>
array2 array 형태 :  (2, 3)
[[1 2 3]
 [2 3 4]]
array3 type :  <class 'numpy.ndarray'>
array3 array 형태 :  (1, 3)
[[1 2 3]]


In [3]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


In [4]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)
#list를 int형으로 자동으로 변환

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [5]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype) #int형이 유니코드 문자열 값으로 변환되었다.

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype) #int형이 float64로 변환되었다.
#만약 다른 데이터 유형이 섞여있는 리스트를 ndarray로 변경할 시
#데이터 크기가 더 큰 데이터 타입으로 형 변환을 일괄 적용한다.

['1' '2' 'test'] <U11
[1. 2. 3.] float64


In [6]:
#ndarray 내 데이터값의 타입 변경은 astype() 메서드를 이용한다.
#메모리를 절약해야할 때 이용된다.
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1= array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2= array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


In [7]:
sequence_array = np.arange(10) #default 함수 인자는 stop값이며 0부터 stop값인 10에서 -1까지의 연속 숫자 값을 배열에 넣는다.
sequence_array2 = np.array(range(10))
sequence_array3 = np.arange(1,11) #arange(x, y) = x이상부터 y미만까지의 값을 배열에 넣는다.
print(sequence_array)
print(sequence_array2)
print(sequence_array3)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
int32 (10,)


In [8]:
zero_array = np.zeros((3, 2),dtype = 'int32') #dtype을 지정하지 않으면 float64형태로 저장한다.
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3, 2)) #dtype을 지정하지 않으면 float64형태로 저장한다.
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [9]:
array1 = np.arange(10)
print('array1:\n', array1)

array2 = array1.reshape(2,5) #ndarray를 특정 차원 및 크기로 변환한다.
print('array2:\n',array2)

array3 = array1.reshape(5,2)
print('array3:\n',array3)

array1:
 [0 1 2 3 4 5 6 7 8 9]
array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [10]:
array1.reshape(4,3) #단, 지정된 사이즈로 변경이 불가능하면 오류가 발생한다.

ValueError: cannot reshape array of size 10 into shape (4,3)

In [ ]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1,5) #인자를 -1로 넣으면 원래 ndarray와 호환되는 새로운 shape로 변환해준다.
print('array2 shape:',array2.shape)

array3 = array1.reshape(5,-1)
print('array3 shape:',array3.shape)

In [ ]:
array1 = np.arange(10)
array4 = array1.reshape(-1,4) #물론 -1을 사용하더라고 호환될 수 없는 형태는 반환할 수 없다.

In [ ]:
array1 = np.arange(12)
print(array1)

array2 = array1.reshape(2, 2, -1) #3차원으로 변환
print('array2 shape:',array2.shape)

In [ ]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n',array3d.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1,1)
print('array5:\n',array5.tolist())
print('array5 shape:',array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1,1)
print('array6:\n',array6.tolist())
print('array6 shape:',array6.shape)

#reshape(-1,1)이 자주 사용되는 이유
#여러개의 넘파이 ndarray는 stack이나 concat으로 결합될 때 각각의 ndarray의 형태를 통일해 유용하게 사용된다.


In [ ]:
#그럼 stack과 concat이 뭘까?
#두개의 ndarray를 합치는 기능은 동일하나 stack이 더 제약이 많다.
a = np.array([[1, 2], [3, 4]]) # a.shape=(2, 2)
b = np.array([[5, 6]]) # b.shape=(2, 1)

In [ ]:
print(np.concatenate((a, b), axis = 0)) # concatenate 함수는 합칠 axis를 제외한 shape 값을 제외하고 일치하면 가능하다.

In [ ]:
print(np.stack((a, b), axis=0)) # stack 함수는 합치려는 배열들의 shape가 전부 동일해야합니다. 

In [ ]:
a = np.array([[1, 2], [3, 4]]) # a.shape=(2, 2)
b = np.array([[5, 6], [7, 8]]) # b.shape=(2, 2)

In [ ]:
print(np.concatenate((a, b), axis = 0)) #shape = (4, 2)

In [ ]:
print(np.stack((a, b), axis=0)) #shape = (2, 2, 2)
#stack 함수는 지정한 axis를 완전히 새로운 axis로 생각하게 됩니다.

# Indexing

- 단일값 추출